### ISSUE TITLE
Tracking issue for Windows support

### ISSUE THREAD

**Issue by Acconut** [kvz/lanyon#2]

**Comment by kvz** [comment]
While I made little progress on Native Windows support, if you have Windows 10, it can work with these steps:

- Install BashOnWindows https://msdn.microsoft.com/en-us/commandline/wsl/install_guide#enable-the-windows-subsystem-for-linux-feature-command-line (one trick is to start PowerShell "as an Administrrator" when following that tutorial. When all is done just type `bash` from PowerShell to enter an ubuntu environment)
- `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`
- `sudo apt-get install -y nodejs ruby build-essential`
- `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"`
- `PATH="$HOME/.linuxbrew/bin:$PATH"`
- `echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile`
- Ensure unix `LF` line-endings in Atom via https://atom.io/packages/line-ending-selector

**Comment by Acconut** [comment]
The instructions above are likely outdated and native Windows support will probably not be coming in the soon future, so I am going to close this.
