### ISSUE TITLE
Add textlint?

### ISSUE THREAD

**Issue by arturi** [kvz/lanyon#8]
I think you were planning on adding some markdown linting, have you seen https://textlint.github.io/?

<img width="1089" alt="screen shot 2017-02-11 at 4 18 07 pm" src="https://cloud.githubusercontent.com/assets/1199054/22857591/b01d9d46-f075-11e6-82a0-8b64e70766c6.png">

**Comment by kvz** [comment]
I have not and this looks like _just the thing_, thanks for sharing! ❤️

**Comment by kvz** [comment]
Just found https://github.com/webpack/webpack.js.org/blob/master/.proselintrc

**Comment by kvz** [comment]
with the new direction of lanyon, it's probably better to not bundle this, but just use it in the repo where we need it :ok_hand:
